### ISSUE TITLE
Document how to style a SVG image for dark theme

### ISSUE THREAD

**Issue by stuartrowe** [jenkinsci/customizable-header-plugin#83]
### Describe your use-case which is not covered by existing documentation.

The current documentation suggests using an SVG image:
> Ideally you use an SVG as they can be made working nicely with the dark theme

However I'm not sure how to configure this either in the SVG itself or with a custom theme CSS file.

Looking at the generated HTML, the .svg file is included through an `<img>`. As I understand it this doesn't allow for embedding a style block in the .csv such as:

```html
<style>
    svg path {
        fill: #151616;
    }
    @media (prefers-color-scheme: dark) {
    svg path {
        fill: #EAE9E9;
    }
</style>
```

And I was unable to get something like below working with a custom CSS file:
```CSS
.custom-header__logo {
	fill: #151616;
}

@media (prefers-color-scheme: dark) {
	.custom-header__logo {
		fill: #EAE9E9;
	}
}
```

Any guidance on this would be appreciated.
